### ISSUE TITLE
Help on a dynamically generated args list

### ISSUE THREAD

**Issue by CGenie** [andreas/ocaml-graphql-server#155]
Hello,
First of all thank you for this great library :)
I have a list of fields with variable type, something along the lines of:
```ocaml
type typ = INTEGER | STRING;
type t = {
  name: string;
  typ: typ;
};
```
and I make a list of `Graphql.Schema.field` like this:
```ocaml
let field_convert f =
  match f.typ with
    | INTEGER -> field f.name ~typ:int ~args:Arg.[] ~resolve(...)
    | STRING    -> field f.name ~typ:string ~args:Arg.[] ~resolve(...)
in
let table_fields = List.map field_convert fields
```
This works fine. However I want to have a list of args as well and when I do the similar:
```ocaml
let arg_convert f =
  match f.typ with
    | INTEGER -> Arg.(arg f.name ~typ:int)
    | STRING    -> Arg.(arg f.name ~typ:string)
(*
in
let table_args = List.map arg_convert fields
(* yeah I know Arg.[] is not a list, so List.map won't work here *)
*)
```
I get an error compiling `arg_convert`:
```
Error: This expression has type string option arg
       but an expression was expected of type int option arg
       Type string is not compatible with type int 
```

Do you have an idea how can I overcome this? I.e. to unify the return type of `arg_convert` so that it works similar to `field_convert`?

**Comment by andreas** [comment]
> Do you have an idea how can I overcome this? I.e. to unify the return type of `arg_convert` so that it works similar to `field_convert`?

I think it depends how you use `arg_convert` later. If this is for inserting into a sqlite table with `graphql-sqlite`, could you convert input value to a [`Sqlite3.Data.t`](http://mmottl.github.io/sqlite3-ocaml/api/sqlite3/Sqlite3/Data/index.html#type-t)? Otherwise it would be helpful with more context 😄

**Comment by CGenie** [comment]
This is precisely the thing im working on, will check it out, thanks!

**Comment by CGenie** [comment]
Yes, indeed, I'm asking about `graphql-sqlite`, will check out your tip, thanks! :)

**Comment by CGenie** [comment]
OK so I still don't get this fully. It's about this code:
https://gitlab.com/cgenie/graphql-sqlite/blob/master/lib/graphql_sqlite.ml
I'm trying to automatically generate args corresponding to all sqlite columns using a function of this form:
```ocaml
let arg_convert _db _idx f =
  let open Schema in
  let open Sqlite3_field in

  match f.typ with
    | INTEGER -> Arg.(arg f.name ~typ:int)
    | TEXT    -> Arg.(arg f.name ~typ:string)
    | BLOB    -> Arg.(arg f.name ~typ:string)
    | REAL    -> Arg.(arg f.name ~typ:float)
    | NUMERIC -> Arg.(arg f.name ~typ:float)
```
(yeah I know I have my own enum and don't use `Sqlite3.Data.t` maybe I'll refactor later).
Anyways I need a function of this form somewhere to collect all args into one list (or should I write `Arg.[]`). In utop I have this:
```ocaml
OCaml # let x = Graphql.Schema.Arg.((arg "x" ~typ:string)::[]);;
val x : ('_weak12, string option -> '_weak12) Graphql.Schema.Arg.arg_list =
  Graphql.Schema.Arg.(::) (<abstr>, Graphql.Schema.Arg.[])
OCaml # Graphql.Schema.Arg.((arg "y" ~typ:int)::x);;
- : ('_weak13, int option -> string option -> '_weak13)
    Graphql.Schema.Arg.arg_list
=
Graphql.Schema.Arg.(::) (<abstr>,
 Graphql.Schema.Arg.(::) (<abstr>, Graphql.Schema.Arg.[])
```
so in fact I can collect different arg types into one `Arg.[]`. The point is that I want a function to do this and OCaml complains about the return types of this function.

**Comment by andreas** [comment]
Ok, I think I have a better understanding of what you want to achieve now. Dynamically generating arguments is one of the most tricky parts to do with this library due to the types used for arguments and resolvers. In particular, you have to convince the type checker that the resolver and argument list for a field agree on the number of type of arguments.

The only way to do this (that I'm aware of anyway), is to inductively construct the resolver and argument "together", and hide the type of the resolve function using an existential type (via GADTs). To that end, you might define a type like this:

```ocaml
type 'a dynamic_resolver =
  Dynamic_resolver : 'b * ('a, 'b) Schema.Arg.arg_list -> 'a dynamic_resolver
```

This encapsulates a single resolve function and an argument list that agree. Using `dynamic_resolver`, you can recursively build up a resolve function and argument list step by step. The general formula is something like this:

```ocaml
let rec create_dynamic_resolver foos =
  match foos
  | [] -> Dynamic_resolver (some_value, Schema.Arg.[])
  | foo::rest ->
    let Dynamic_resolver (f, args) = create_dynamic_resolver rest in
    let arg = (* create argument from foo *) in
    let f' x = (* type of arg and x agree. Use f in here *) in
    Dynamic_resolver (f', Schema.Arg(arg::args)
```

Before applying the above formula to your use case, there's another wrinkle regarding the argument types that have to be converted to `Sqlite3.Data.t`:

```ocaml
type sqlite_arg =
  | Sqlite_arg : 'a Schema.Arg.arg * ('a -> Sqlite3.Data.t) -> sqlite_arg

let field_to_arg f =
  match f.Sqlite3_field.typ with
    | INTEGER ->
        Sqlite_arg (
          Schema.Arg.(arg f.name ~typ:(non_null int)),
          fun x -> Sqlite3.Data.INT (Int64.of_int x)
        )
    | TEXT ->
        Sqlite_arg (
          Schema.Arg.(arg f.name ~typ:(non_null string)),
          fun x -> Sqlite3.Data.TEXT x
        )
    | BLOB ->
        Sqlite_arg (
          Schema.Arg.(arg f.name ~typ:(non_null string)),
          fun x -> Sqlite3.Data.BLOB x
        )
    | REAL
    | NUMERIC ->
        Sqlite_arg (
          Schema.Arg.(arg f.name ~typ:(non_null float)),
          fun x -> Sqlite3.Data.FLOAT x
        )
```

So `sqlite_arg` encapsulates a GraphQL argument that can be converted to a `Sqlite3.Data.t`.

With that in hand, we can create a function for defining a dynamic resolver based on a list of `Sqlite3_field`s. There are probably multiple ways to approach this -- here's one:

```ocaml
let rec dynamic_resolver_of_fields fields stmt idx f =
  match fields with
  | [] -> Dynamic_resolver (f stmt, Schema.Arg.[])
  | field::rest ->
      let Dynamic_resolver (resolve, args) = dynamic_resolver_of_fields rest stmt (idx+1) f in
      let Sqlite_arg (a, to_data) = field_to_arg field in
      let resolver x = 
        let data = to_data x in
        let Sqlite3.Rc.OK = Sqlite3.bind stmt idx data in (* <-- poor error handling *)
        resolve
      in
      Dynamic_resolver (resolver, Schema.Arg.(a::args))
```

where

- `fields` is a list of `Sqlite3_field`s.
- `stmt` is a `Sqlite3.stmt` that is assumed to have `n` free variables, where `n = List.length fields`.
- `idx` is the index of next free variable to be bound.
- `f` is a function to apply to the statement with all parameters bound. I expect this should run the statement and return some kind of result.

Hope it helps 😄

**Comment by andreas** [comment]
@CGenie Did the above make sense? Let me know if you need further input to make progress 😄

**Comment by CGenie** [comment]
It did make sense and I started to work on it, however I didn't have much time since then.
What I have currently is:
https://gitlab.com/cgenie/graphql-sqlite/blob/args/lib/graphql_sqlite.ml#L23-69
however I still get:
```
File "lib/graphql_sqlite.ml", line 139, characters 12-16:
Error: This expression has type (string, $Dynamic_resolver_'b) Arg.arg_list
       but an expression was expected of type
         (('a list, string) result Lwt.t, 'b) Arg.arg_list
       Type string is not compatible with type ('a list, string) result Lwt.t
```
I guess I still need to fix the resolver. Anyways am loaded with other work now, this is a side project. I can close this issue however to keep your repo clean :)

**Comment by sgrove** [comment]
It'd be great to have a list of examples in the repo, and I suspect this
would be a gem in there!

**Comment by andreas** [comment]
> I guess I still need to fix the resolver.

Yeah, it seems like nothing is actually being done with the statement once the variables have been bound (the `f x -> x` part): https://gitlab.com/cgenie/graphql-sqlite/blob/args/lib/graphql_sqlite.ml#L135

> I can close this issue however to keep your repo clean :) You helped me more than I expected :)

Cool, let me know if you need more input 😄
