### ISSUE TITLE
Context for nested resolver functions

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#43]
I have a query with roughly this structure:

```graphql
tweet(apiKey: "my-twitter-api-key", id: "1") {
  body
  user {
    followers {
      # Needs access to above apiKey when resolving since we need to
      # make another request
      username
      followerCount
    }
  }
}
```

In order to get to the `followers` edge, I have to have (in a previous resolver) had a valid API key. Right now my resolver looks like this (hope the reason syntax is ok!):
```rust
makeIOField
              "followers"
              (non_null (list (non_null twitterUser)))
              (
                fun () (twitterUser: twitterUser) =>
                  List.map
                    (
                      fun twitterUserId =>
                        /* I don't have access to twitterApiKey here! */
                        getTwitterUser twitterApiKey twitterUserId
                    )
                    twitterUser.followerIds
              )
```

Is there some sort of contextual structure that I can look in to find out what the api key would be, or perhaps some other way of solving this step?

**Comment by andreas** [comment]
On top of my head, there are three ways to solve this:

1. Pass the API key explicitly down to nested resolvers by changing the source type of "TwitterUser" from `user` to `user * string` (the string being the API key). This is a little cumbersome and will require changing the resolvers on fields of "TwitterUser", but is the most clean in terms of separation between domain logic and GraphQL. Example of `followers` resolver:

    ```ocaml
    fun () (twitterUser, twitterApiKey) ->
      List.map (fun twitterUserId ->
        getTwitterUser twitterApiKey twitterUserId
      ) twitterUser.followerIds
    ```

2. Add API key to your user type, e.g. `type twitterUser = { followerIds : int list; apiKey : string; ... }`. This pollutes your domain model, but is more convenient than solution 1. Example of `followers` resolver:

    ```ocaml
    fun () twitterUser ->
      List.map (fun twitterUserId ->
        getTwitterUser twitterUser.twitterApiKey twitterUserId
      ) twitterUser.followerIds
    ```

3. Put the API key in the context. It looks like your context type is currently `unit`, but you could use a record type instead, e.g. `type appContext = { twitterApiKey : string }`. Example of `followers` resolver:
    ```ocaml
    fun ctx twitterUser ->
      List.map (fun twitterUserId ->
        getTwitterUser ctx.twitterApiKey twitterUserId
      ) twitterUser.followerIds
    ```
    This is a little dirty, but very convenient.

Hope this helps :)

**Comment by sgrove** [comment]
Are there examples of using records as context? Having some trouble figuring it out.

**Comment by andreas** [comment]
The `ctx` argument that you pass to `Schema.execute` is basically given as the first argument to all resolvers. Typically it's used to hold database connections or other shared data that would otherwise be in global variables. You can also use it to pass information between resolvers, though it comes with a big caveat that I should probably have mentioned above (see below).

For your case, it would be something like this:

```ocaml
type app_ctx = {
  mutable api_key : string;
}

let ctx = { api_key = "" } in
Graphql_lwt.Schema.execute my_schema ctx my_query
```

In your "tweet"-resolver you can then do `ctx.api_key <- new_api_key`, and this will be available in the "followers"-resolver.

The big caveat is that in the context of concurrency, you cannot be certain what order the resolvers evaluate in. Maybe you can work around this in a problem-specific manner -- it depends on your use case.

Alternatively you can go for option 1 or 2...

**Comment by sgrove** [comment]
Hrm, I expected that the context was shared per-query as in, if I create a
record with twitterKeyA and then concurrently kick off another query using
a record with twitterKeyB, they wouldn't clash in any way.

For some reason, using your example the type checker still wants it to be
unit, probably because some resolver somewhere uses unit. Is there some way
to add a local type annotation to `Graphql_lwt.Schema.execute my_schema ctx
my_query` to force the rest of the program to use `app_ctx` so I can easily
clean up all the existing units?

**Comment by andreas** [comment]
> I expected that the context was shared per-query [...]

The context can be independent per query, just create a new context value for every call to `Schema.execute`.

Currently contexts are implemented similarly to `graphql-js` and `graphql-go`, but maybe there's a better way to do it. Possibly something along the line of context modifications being local to each part of the query evaluation. I'm not aware of any other GraphQL libraries that address your problem in a particularly elegant manner, but I'd be happy to learn I was wrong :)

> Is there some way to add a local type annotation to `Graphql_lwt.Schema.execute my_schema ctx my_query` to force the rest of the program to use `app_ctx` so I can easily clean up all the existing units?

You can add type annotations when you construct the schema and/or any types in the schema, i.e.

```ocaml
open Graphql_lwt
let foo : (app_ctx, some_source_type) Schema.typ = Schema.(
  (* ... *)
)
```

**Comment by sgrove** [comment]
That worked out well, thank you! Just took a lot of scraping through my existing code to find all references to unit, and adding some explicit annotations to get the compiler to believe me that I wanted my record type instead of unit.

It'd be good to update the example to have a context record instead of unit though, so others know how to reach for it.

**Comment by turboMaCk** [comment]
Hi 👋 

sorry for spamming closed issue once again. I was trying to solve a very similar thing today and I did succeed even though this was quite challenging to me (no experience with language and ecosystem). I would just like to validate my solution (or at least share it for future human).

I'm implementing GraphQL proxy service which under the hood collects data from REST APIs. Those APIs are using [Bearer token](https://tools.ietf.org/html/rfc6750). In GraphQL this token is part of variables (`{ "token": "xxx" }`).

I'm using `ctx` (context) to store this value so it's accessible in all resolvers (no need to pass it as a variable).

```ocaml
type app_ctx = {
    token : string option;
  }
```

An option is used as some queries might require authentication.

I was trying to make sense of suggestion mentioned above in this thread. I've started with code similar to the example so my main was essentially this:

```ocaml
let () =
  Server.start ~ctx:(fun () -> ()) schema
  |> Lwt_main.run
```

Anyway at least in my case token identifies a user and since `Server` module has `ctx` constructor with type `unit -> 'ctx` I don't think it is possible to use this implementation for a case where `ctx` has to be constructed from `~variables` decoded from request body. This is why I've copied code from [`Server` module](https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-lwt/src/graphql_lwt.ml#L5-L52) and start changes here.

First important change is that I've needed pass `make_ctx` function further to `execute_request` as in `mk_callback` I had no data to pass in the argument yet.

In `execute_request` I'm reusing `variables` constant and passing it to `make_cfx` (the `cfx` constructor) so this function can use it to construct `app_ctx` record.

This is how `AppServer` module looks like with those changes:

```ocaml
module AppServer = struct
  module C = Cohttp_lwt_unix
  open Lwt

  let static_file_response ?(encoding=`None) path =
    match Assets.read path with
    | Some body -> C.Server.respond_string ~status:`OK ~body ()
    | None -> C.Server.respond_string ~status:`Not_found ~body:"" ()

  let json_err = function
    | Ok _ as ok -> ok
    | Error err -> Error (`String err)

  let execute_query ctx schema variables query =
    let open Lwt_result in
    Lwt.return @@ json_err @@ Graphql_parser.parse query >>= fun doc ->
    Schema.execute schema ctx ~variables doc

  let execute_request make_ctx schema req body =
    Cohttp_lwt.Body.to_string body >>= fun body' ->
    Lwt_io.printf "Body: %s\n" body';
    let json = Yojson.Basic.from_string body' in
    let query = Yojson.Basic.(json |> Util.member "query" |> Util.to_string) in
    let variables = try Yojson.Basic.Util.(json |> member "variables" |> to_assoc) with _ -> [] in
    let ctx = make_ctx variables in
    Lwt_io.printf "Query: %s\n" query;
    let result = execute_query ctx schema (variables :> (string * Graphql_parser.const_value) list) query in
    result >>= function
    | Ok data ->
       let body = Yojson.Basic.to_string data in
       C.Server.respond_string ~status:`OK ~body ()
    | Error err ->
       let body = Yojson.Basic.to_string err in
       C.Server.respond_error ~body ()

  let mk_callback mk_context schema conn (req : Cohttp.Request.t) body =
    Lwt_io.printf "Req: %s\n" req.resource;
    let req_path = Cohttp.Request.uri req |> Uri.path in
    let path_parts = Str.(split (regexp "/") req_path) in
    match req.meth, path_parts with
    | `GET,  ["graphql"]       -> static_file_response "index.html"
    | `GET,  ["graphql"; path] -> static_file_response path
    | `POST, ["graphql"]       -> execute_request mk_context schema req body
    | _ -> C.Server.respond_string ~status:`Not_found ~body:"" ()

  let start ?(port=8080) ~ctx schema =
    let callback = mk_callback ctx schema in
    C.Server.create ~mode:(`TCP (`Port port)) (C.Server.make ~callback ())
end
```

Next (challenging) piece of work was to dive to [`Yojson`](https://github.com/mjambon/yojson) to get the data from a body (which requires surprisingly low-level manipulation with AST).

First I've defined helper function `filter_map : ('a -> 'a option) -> 'a list -> 'a option`:

```ocaml
let find_map fc list =
  List.fold_right (fun a acc -> match fc a with
                                | None -> acc
                                | r -> r
    ) list None
```

This function is useful in updated "main" where I'm doing actual work of getting token from requests:

```ocaml
let () =
  let
    make_ctx variables = { token = find_map (function
                                       | ("token", `String token) -> Some token
                                       | _ -> None)
                                     variables }
  in
  AppServer.start ~ctx:(make_ctx) AppSchema.schema
  |> Lwt_main.run
```

And that's it. I'm really glad that I've solved it myself. Anyway, if any of you has any suggestion how to do the same thing in a more elegant way I would be very happy to throw this code away. If you don't have time to help me it's fine though.

**Comment by andreas** [comment]
Great job working that out 👍

Indeed the current type `unit -> 'ctx` for `~ctx` is a bit limited. It seems your proposed solution changes the type to `Yojson.Basic.json -> 'ctx`, which is more flexible. I think using variables to contain the token is a bit unusual though: variables are intended to be used in the GraphQL query.

I think a more general solution would be to change the type of `~ctx` to `Cohttp.Request.t -> 'ctx`, i.e. a function from the HTTP request to some context value. This would be very flexible, and you could pass the token via a HTTP header, a query parameter or another POST body entry. If you're up for implementing that, I'd very much welcome such a PR.

**Comment by turboMaCk** [comment]
Agree. I've used variables for now so so I can easily play with it using Graphical. Also, I agree with an idea of having full `Cohttp.Request.t -> 'ctx` and let user decide which parts of a request to use to construct `'ctx` is probably a way to go.

**Comment by andreas** [comment]
@turboMaCk I've implemented this idea now (https://github.com/andreas/ocaml-graphql-server/pull/88) 😄
